### ISSUE TITLE
Finish moderation config section

### ISSUE THREAD

**Issue by SpyTec** [RheaAyase/Botwinder.web#49]
Moderation section requires:

- [x] RoleSelector #30 
- [x] Searchable role dropdown (#34) for `operator_roleid`
- [x] Textarea for `quickban_reason`
- [x] Number field for `quickban_duration`
- [x] Searchable role dropdown (#34) for `mute_roleid`
- [x] Searchable channel dropdown (#34) for `mute_ignore_channelid`
- [x] Links for moderation guidelines and moderation discussion, as seen in live implementation.
