### ISSUE TITLE
Finish logging config section

### ISSUE THREAD

**Issue by SpyTec** [RheaAyase/Botwinder.web#50]
Logging section requires:

- [x] Searchable channel dropdown (#34) for `mod_channelid`
- [x] Switch for `embed_modchannel`
- [x] Switch for `log_bans`
- [x] Color picker (#38) for `color_modchannel`
- [x] Switch for `log_warnings`
- [x] Color picker (#38) for `color_logwarning`
- [x] Searchable channel dropdown (#34) for `log_channelid`
- [x] Switch for `embed_logchannel`
- [x] Switch for `log_editedmessages`
- [x] Switch for `log_deletedmessages`
- [x] Color picker (#38) for `color_logmessages`
- [x] Switch for `log_promotions`
- [x] Searchable channel dropdown (#34) for `voice_channelid`
- [x] Switch for `embed_voicechannel`
- [x] Color picker (#38) for `color_voicechannel`
- [x] Searchable channel dropdown (#34) for `activity_channelid`
- [x] Switch for `embed_activitychannel`
- [x] Color picker (#38) for `color_activitychannel`
- [x] Switch for `log_join`
- [x] Textarea for `log_message_join`
- [x] Switch for `log_mention_join`
- [x] Switch for `log_timestamp_join`
- [x] Switch for `log_leave`
- [x] Textarea for `log_message_leave`
- [x] Switch for `log_mention_leave`
- [x] Switch for `log_timestamp_leave`
- [x] Ignored channels selector (#39)
